baseURL = 'https://omatko.pwr.edu.pl/'
relativeURLs = true
canonifyURLs = true
languageCode = 'pl-PL'
title = 'OMatKo!!!'
theme = '2025'

defaultContentLanguage = "pl"
[languages]
[languages.pl]
languageName = "Polski"

[menus]
[[menus.main]]
name = 'O konferencji'
url = '/#about'
weight = 1

[[menus.main]]
name = 'Aktualności'
pageRef = 'aktualnosci'
url = '/aktualnosci'
weight = 2


[[menus.main]]
name = 'Organizatorzy'
pageRef = 'organizatorzy'
url = '/organizatorzy'
weight = 3

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]


[params]
# Harmonogram
show_schedule_section = true

# Rejestracja 
show_registration = false

# Linki do formularzy
participant_url = 'https://conf.e-science.pl/event/116/registrations/93/?form_token=90d6c5f5-6e67-470e-afab-1f9a66603f27'
speaker_url = 'https://conf.e-science.pl/e/omatko2025'
poster_url = 'https://conf.e-science.pl/e/omatko2025'

# Data udostępnienia zapisów

participant_reg_open_date = '2025-10-22'
active_reg_open_date = '2025-10-02'

# Data zamkniecia zapisów

participant_reg_close_date = '2025-11-25'
active_reg_close_date = '2025-10-31'

# Zamkniecie zapisów

participant_reg_close = true
active_reg_close = true


# Sponsorzy
show_sponsors_section = true

# Patroni medialni i honorowi
show_patrons_section = true



# Animacja w tle
enable_background_animations = true

show_regulamin = true

math = true

enable_voting = true

vote_app_url = "https://omatko.pwr.edu.pl/glosuj/"
