baseURL = 'https://omatko.im.pwr.edu.pl/'
relativeURLs = true
canonifyURLs = true
languageCode = 'pl-PL'
title = 'OMatKo!!!'
theme = '2025'

defaultContentLanguage = "pl"
[languages]
[languages.pl]
languageName = "Polski"

[menus]
[[menus.main]]
name = 'O konferencji'
url = '/#about'
weight = 1

[[menus.main]]
name = 'Aktualno≈õci'
pageRef = 'aktualnosci'
url = '/aktualnosci'
weight = 2


# [[menus.main]]
# name = 'Organizatorzy'
# pageRef = 'organizatorzy'
# url = '/organizatorzy'
# weight = 3

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]


[params]
# Harmonogram
show_schedule_section = false

# Rejestracja 
show_registration = true

# Linki do formularzy
participant_url = ''
speaker_url = ''
poster_url = ''

# Sponsorzy
show_sponsors_section = false

# Patroni medialni
show_patrons_section = false

# Animacja w tle
enable_background_animations = true

math = true
